In [1]:
import numpy as np

In [2]:
board = np.zeros((9,9))
board

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
indices = [(i, j) for i in range(9) for j in range(9)]
board[indices[0]]

0.0

In [21]:
def get_indices(N: int)-> list:
    return [(i, j) for i in range(N) for j in range(N)]

In [4]:
'5...8..49...5...3..673....115..........2.8..........187....415..3...2...49..5...3'

1

In [13]:
8%9

8

In [35]:
def load_board(initial: str, N: int = 9)-> np.array:
    board = np.zeros((9,9), dtype=int)
    j= 0
    for k, char in enumerate(initial):
        if char == '.':
            pass
        else:
            i = k // N
            j = k % N
            board[i, j] = int(char)
    return board

In [82]:
load_board('5...8..49...5...3..673....115..........2.8..........187....415..3...2...49..5...3')

array([[5, 0, 0, 0, 8, 0, 0, 4, 9],
       [0, 0, 0, 5, 0, 0, 0, 3, 0],
       [0, 6, 7, 3, 0, 0, 0, 0, 1],
       [1, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 8],
       [7, 0, 0, 0, 0, 4, 1, 5, 0],
       [0, 3, 0, 0, 0, 2, 0, 0, 0],
       [4, 9, 0, 0, 5, 0, 0, 0, 3]])

In [99]:
board = load_board('5...8..49...5...3..673....115..........2.8..........187....415..3...2...49..5...3')

In [7]:
def fill(board: np.array, index: tuple)-> np.array:
    print(index)
    return board

In [8]:
for index in indices:
    if board[index] == 0:
        board = fill(board, index)
    else:
        pass

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(0, 7)
(0, 8)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(1, 7)
(1, 8)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(3, 5)
(3, 6)
(3, 7)
(3, 8)
(4, 0)
(4, 1)
(4, 2)
(4, 3)
(4, 4)
(4, 5)
(4, 6)
(4, 7)
(4, 8)
(5, 0)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 5)
(5, 6)
(5, 7)
(5, 8)
(6, 0)
(6, 1)
(6, 2)
(6, 3)
(6, 4)
(6, 5)
(6, 6)
(6, 7)
(6, 8)
(7, 0)
(7, 1)
(7, 2)
(7, 3)
(7, 4)
(7, 5)
(7, 6)
(7, 7)
(7, 8)
(8, 0)
(8, 1)
(8, 2)
(8, 3)
(8, 4)
(8, 5)
(8, 6)
(8, 7)
(8, 8)


In [49]:
def get_cell(index: tuple, N: int = 9):
    cell_size = int(np.sqrt(N))
    return (index[0] // cell_size, index[1] // cell_size)

def get_affected_indices(index: tuple, N: int = 9)-> list:
    '''affected positions according to sudoku rules'''
    rows = {(index[0], j) for j in range(N)}
    cols = {(j, index[1]) for j in range(N)}
    cell = {
        (i, j)  for i in range(N) for j in range(N)\
        if get_cell(index, N) == get_cell((i, j), N)
    }
    return list(
        rows.union(cols).union(cell)
    )
    
def get_occupied_vals(index: tuple, board: np.array, N: int = 9)-> list:
    '''what are the used values according to sudoku rules'''
    values = {board[tup] for tup in get_affected_indices(index, N)}
    return [x for x in values if x != 0]

def get_candidates(board: np.array, N: int = 9)-> dict:
    '''board element at index is empty (0)'''
    indices = get_indices(N)
    candidates = {}
    for index in indices:
        if board[index] == 0:
            candidates[index] = [
                x for x in range(1, 10) if x not in get_occupied_vals(index, board)
            ]
    return candidates

In [22]:
int(np.sqrt(9))

3

In [28]:
{
    board[i, j]  for i in range(N) for j in range(N)\
    if get_cell(index, N) == get_cell((i, j), N)
}

{0.0, 1.0, 3.0, 5.0}

In [29]:
index

(8, 8)

In [89]:
board

array([[5, 0, 0, 0, 8, 0, 0, 4, 9],
       [0, 0, 0, 5, 0, 0, 0, 3, 0],
       [0, 6, 7, 3, 0, 0, 0, 0, 1],
       [1, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 8],
       [7, 0, 0, 0, 0, 4, 1, 5, 0],
       [0, 3, 0, 0, 0, 2, 0, 0, 0],
       [4, 9, 0, 0, 5, 0, 0, 0, 3]])

In [50]:
get_occupied_vals(index, board)

[1, 3, 4, 5, 8, 9]

In [90]:
get_candidates(board)

{(0, 1): [1, 2],
 (0, 2): [1, 2, 3],
 (0, 3): [1, 6, 7],
 (0, 5): [1, 6, 7],
 (0, 6): [2, 6, 7],
 (1, 0): [2, 8, 9],
 (1, 1): [1, 2, 4, 8],
 (1, 2): [1, 2, 4, 8, 9],
 (1, 4): [1, 2, 4, 6, 7, 9],
 (1, 5): [1, 6, 7, 9],
 (1, 6): [2, 6, 7, 8],
 (1, 8): [2, 6, 7],
 (2, 0): [2, 8, 9],
 (2, 4): [2, 4, 9],
 (2, 5): [9],
 (2, 6): [2, 5, 8],
 (2, 7): [2, 8],
 (3, 2): [2, 3, 4, 6, 8, 9],
 (3, 3): [4, 6, 7, 9],
 (3, 4): [3, 4, 6, 7, 9],
 (3, 5): [3, 6, 7, 9],
 (3, 6): [2, 3, 4, 6, 7, 9],
 (3, 7): [2, 6, 7, 9],
 (3, 8): [2, 4, 6, 7],
 (4, 0): [3, 6, 9],
 (4, 1): [4, 7],
 (4, 2): [3, 4, 6, 9],
 (4, 4): [1, 3, 4, 6, 7, 9],
 (4, 6): [3, 4, 5, 6, 7, 9],
 (4, 7): [6, 7, 9],
 (4, 8): [4, 5, 6, 7],
 (5, 0): [2, 3, 6, 9],
 (5, 1): [2, 4, 7],
 (5, 2): [2, 3, 4, 6, 9],
 (5, 3): [4, 6, 7, 9],
 (5, 4): [3, 4, 6, 7, 9],
 (5, 5): [3, 5, 6, 7, 9],
 (5, 6): [2, 3, 4, 5, 6, 7, 9],
 (6, 1): [2, 8],
 (6, 2): [2, 6, 8],
 (6, 3): [6, 8, 9],
 (6, 4): [3, 6, 9],
 (6, 8): [2, 6],
 (7, 0): [6, 8],
 (7, 2): [1, 5, 6, 8],
 

In [100]:
candidates = get_candidates(board)

In [52]:
board.shape[0]

9

In [107]:
def update_value(index: tuple, board: np.array, candidates: dict)-> np.array:
    '''
    for an index with a valid answer, fill the answer value and update
    relevant candidates
    '''
    fill = candidates[index][0] # THE valid answer
    board[index] = fill
    indices_to_check = get_affected_indices(index, board.shape[0])
    for tup in indices_to_check:
        if tup in candidates and fill in candidates[tup]:
            candidates[tup].remove(fill)
    return board, candidates

In [92]:
board

array([[5, 0, 0, 0, 8, 0, 0, 4, 9],
       [0, 0, 0, 5, 0, 0, 0, 3, 0],
       [0, 6, 7, 3, 0, 0, 0, 0, 1],
       [1, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 8],
       [7, 0, 0, 0, 0, 4, 1, 5, 0],
       [0, 3, 0, 0, 0, 2, 0, 0, 0],
       [4, 9, 0, 0, 5, 0, 0, 0, 3]])

In [103]:
board, candidates = update_value((2, 5), board, candidates)

In [104]:
board[1,5], candidates[1,5]

(0, [1, 6, 7])

In [105]:
indices_to_check = get_affected_indices((2, 5), board.shape[0])
for tup in indices_to_check:
    if tup in candidates:
        print(tup, candidates[tup], board[tup])

(2, 4) [2, 4] 0
(2, 7) [2, 8] 0
(1, 5) [1, 6, 7] 0
(0, 5) [1, 6, 7] 0
(2, 5) [] 9
(3, 5) [3, 6, 7] 0
(5, 5) [3, 5, 6, 7] 0
(0, 3) [1, 6, 7] 0
(2, 0) [2, 8] 0
(1, 4) [1, 2, 4, 6, 7] 0
(2, 6) [2, 5, 8] 0
(8, 5) [1, 6, 7] 0


In [106]:
candidates

{(0, 1): [1, 2],
 (0, 2): [1, 2, 3],
 (0, 3): [1, 6, 7],
 (0, 5): [1, 6, 7],
 (0, 6): [2, 6, 7],
 (1, 0): [2, 8, 9],
 (1, 1): [1, 2, 4, 8],
 (1, 2): [1, 2, 4, 8, 9],
 (1, 4): [1, 2, 4, 6, 7],
 (1, 5): [1, 6, 7],
 (1, 6): [2, 6, 7, 8],
 (1, 8): [2, 6, 7],
 (2, 0): [2, 8],
 (2, 4): [2, 4],
 (2, 5): [],
 (2, 6): [2, 5, 8],
 (2, 7): [2, 8],
 (3, 2): [2, 3, 4, 6, 8, 9],
 (3, 3): [4, 6, 7, 9],
 (3, 4): [3, 4, 6, 7, 9],
 (3, 5): [3, 6, 7],
 (3, 6): [2, 3, 4, 6, 7, 9],
 (3, 7): [2, 6, 7, 9],
 (3, 8): [2, 4, 6, 7],
 (4, 0): [3, 6, 9],
 (4, 1): [4, 7],
 (4, 2): [3, 4, 6, 9],
 (4, 4): [1, 3, 4, 6, 7, 9],
 (4, 6): [3, 4, 5, 6, 7, 9],
 (4, 7): [6, 7, 9],
 (4, 8): [4, 5, 6, 7],
 (5, 0): [2, 3, 6, 9],
 (5, 1): [2, 4, 7],
 (5, 2): [2, 3, 4, 6, 9],
 (5, 3): [4, 6, 7, 9],
 (5, 4): [3, 4, 6, 7, 9],
 (5, 5): [3, 5, 6, 7],
 (5, 6): [2, 3, 4, 5, 6, 7, 9],
 (6, 1): [2, 8],
 (6, 2): [2, 6, 8],
 (6, 3): [6, 8, 9],
 (6, 4): [3, 6, 9],
 (6, 8): [2, 6],
 (7, 0): [6, 8],
 (7, 2): [1, 5, 6, 8],
 (7, 3): [1, 6, 7, 8